### ISSUE TITLE
The roi_relation_feature_extractor

### ISSUE THREAD

**Issue by Kenneth-Wong** [KaihuaTang/Scene-Graph-Benchmark.pytorch#25]
## ❓ Questions and Help
I saw that the roi_relation_feature_extractor is Motif-style. Do you mean that all the methods (Motif, IMP, VCTree) you implemented adopt this Motif-style relation feature extractor although their original implementations do not extract features in such a way? In other words, all the methods are only different in terms of the "predictor", right?  Thanks.

**Comment by KaihuaTang** [comment]
Yes, the difference among these proposed methods are mainly in their context module, i.e., "predictor" (where their main contributions reside), so I adopt the same feature extractor for fair comparisons (I consider these are tricks rather than core functions).  Otherwise, methods like IMP would be far worse than MOTIFS and VCTree, simply because not applying these "tricks".

**Comment by Kenneth-Wong** [comment]
Wow, thanks for your insightful and timely reply!
