### ISSUE TITLE
Pretrained checkpoint

### ISSUE THREAD

**Issue by qrzou** [KaihuaTang/Scene-Graph-Benchmark.pytorch#5]
Hi, is it possible for you to provide the pre-trained checkpoints for TDE models. I want to try inference with your pretrained models. Thank you!

**Comment by KaihuaTang** [comment]
I can upload several TDE models later for your reference, but upload all of them would be too much (Predcls/sgcls/sgdet  *  motifs/vctree/vtranse *  sum/gate = 18 models). Besides, if you follow the instruction, it only takes several hours (2GPU) to get one, and the performance would be very close or even better, since I don't adjust the hyperparameters.

**Comment by qrzou** [comment]
Thanks a lot! My GPU is too slow.
