### ISSUE TITLE
ImportError: cannot import name '_C' from 'maskrcnn_benchmark'

### ISSUE THREAD

**Issue by Kritz23** [KaihuaTang/Scene-Graph-Benchmark.pytorch#60]
## ❓ Questions and Help
Hi, @KaihuaTang I am facing this issue with almost every repo I am trying to implement on scene graphs. Can you please tell what is the problem here?

from .nms import nms
from maskrcnn_benchmark import _C
ImportError: cannot import name '_C' from 'maskrcnn_benchmark'

**Comment by KaihuaTang** [comment]
I think it is because you failed in building the environment ("python setup.py build develop").

**Comment by Kritz23** [comment]
> I think it is because you failed in building the environment ("python setup.py build develop").

It is building successfully without any error

**Comment by mods333** [comment]
This generally happens due to mismatch in the cudatootkit version of pytorch and that of the complier. To resolve this I would suggest checking the cuda compiler version using `nvcc --version`. In mycase, I have 10.0.
![Screen Shot 2020-07-20 at 12 12 17 PM](https://user-images.githubusercontent.com/8975010/87976750-7e323400-ca82-11ea-83a4-b88dcda77fea.png)
Then in pytorch check the version of cudatookit using `torch.version.cuda`. This version should match that of your cuda compiler. If not then you might have to reinstall pytorch. For example if your nvcc version is 10.1 then you could install pytorch using the command `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`.
Hope that helps

**Comment by Kritz23** [comment]
> I think it is because you failed in building the environment ("python setup.py build develop").

I am not able to figure it out, it's not showing anything like "successfully built" or "Installed" and just ending the build process abruptly. (Trying on Google Colab)

![Screenshot from 2020-07-22 00-51-44](https://user-images.githubusercontent.com/43573202/88097462-cb62f280-cbb5-11ea-8dc5-6192daf63250.png)

Whereas while building apex lib, it is showing like this -
(Installed /usr/local/lib/python3.6/dist-packages/apex-0.1-py3.6-linux-x86_64.egg
Processing dependencies for apex==0.1
Finished processing dependencies for apex==0.1)

![Screenshot from 2020-07-22 00-59-36](https://user-images.githubusercontent.com/43573202/88098205-06b1f100-cbb7-11ea-94e6-897cbd82d178.png)

**Comment by KaihuaTang** [comment]
It looks like you have successfully built the project. Maybe you can try mods333's advice.

**Comment by shipra25jain** [comment]
Hi @KaihuaTang , I am getting the same error. I have ensured that "python setup.py build develop" is built successfully. Also, CUDA version and pytorch's CUDA version are consistent i.e. 10.2 Do you know what could be the problem?

**Comment by shipra25jain** [comment]
Hi @Kritz23 , do you remember how did you fix this error?
Thanks!

**Comment by Kritz23** [comment]
> Hi @Kritz23 , do you remember how did you fix this error?
> Thanks!

If you are working on colab, then its almost impossible. But if you are on a system with gpu, try creating a clean environment and installing everything again step by step given in install.md file.

**Comment by Qi-Chuan** [comment]
hi @shipra25jain , I met the same error:  ImportError: cannot import name '_C' from 'maskrcnn_benchmark' (/home/Users/ssq/Pycharm_Projects/project_mysgg/maskrcnn_benchmark/__init__.py)
Have you fixed the error? Thanks!
